version: '3.1'
  
services:
    mongodb:
        image: mongo:4.0.5
        restart: always
        volumes:
            - /home/docker/data_mongo:/data/db
        networks:
            - pritunl_net
    pritunl:
        image: jippi/pritunl:latest
        restart: always
        privileged: true
        ports:
            - "30477:30477/udp"
            - "30477:30477/tcp"
            - "80:80/tcp"
            - "443:443/tcp"
            - "9700:9700/tcp"
        environment:
            PRITUNL_MONGODB_URI: mongodb://mongodb:27017/pritunl
        volumes:
            - /home/docker/data_pritunl:/var/lib/pritunl
        networks:
            - pritunl_net
networks:
    pritunl_net:
        driver: bridge
